// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYkOMfbgTp0_hVbUN2zN8IxF-h5kA7Hw',
    appId: '1:1018343115284:android:bc08635ee5a436a099b501',
    messagingSenderId: '1018343115284',
    projectId: 'sep-app-9b95e',
    storageBucket: 'sep-app-9b95e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDYMN548U2n2i0VOyobLrg3OlzAPQQ-o',
    appId: '1:1018343115284:ios:453c60a05f7534c499b501',
    messagingSenderId: '1018343115284',
    projectId: 'sep-app-9b95e',
    storageBucket: 'sep-app-9b95e.firebasestorage.app',
    iosBundleId: 'com.app.sep',
  );
}
